### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by blushell** [koennjb/govee-ts#1]
are you able to use this library in nodejs?

**Comment by koennjb** [comment]
Yes, you should be able to use this library in NodeJS with Javascript or TypeScript.

If you have tried using it and have ran into issues, please let me know some more information about the problem here!
Thanks!

**Comment by blushell** [comment]
`const TouchPortalAPI = require('touchportal-api');
import Govee from 'govee-ts';
const TPClient = new TouchPortalAPI.Client();


var client = new Govee("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx");
`

thats my code so far then when i ran to see it i got 

(node:16316) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\JonesTown\Documents\Projects\VSCode\govee-wifi\src\index.js:2
import Govee from 'govee-ts';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`

**Comment by koennjb** [comment]
It looks like your NPM package is set up to use the `require()` syntax to import packages. You should be able to import govee-ts using `const Govee = require('govee-ts');` instead of `import Govee from 'govee-ts';`

Another option is to add the `"type": "module"` property to your package.json which tells Node you want to use the `import` syntax.

[Check out this Stack post](https://stackoverflow.com/questions/61401475/why-is-type-module-in-package-json-file) for more info: 

Hope that helps! Let me know if there's still a problem.

**Comment by blushell** [comment]
so when i use const i get this 

`const Govee = require('govee-ts');

var client = new Govee("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx");`
                               ^

TypeError: Govee is not a constructor


then in the package i tried for the import way and both ways still don't work.
`    "govee-ts": {
      "type": "module",
      "version": "0.1.1",
      "resolved": "https://registry.npmjs.org/govee-ts/-/govee-ts-0.1.1.tgz",
      "integrity": "sha512-3IC9lGXqCMMq/iDZis9bbvTDOWD/f+x+9bh9vY1T1zUCb63YKD4QfxSRYlOcdMgHP+Ck4MixuR9G3IHfzdhpUA==",
      "requires": {
        "axios": "^0.21.1"
      }
    },`


this the first library ive had trouble with not sure what im doing wrong :(

**Comment by koennjb** [comment]
Did some digging and tried importing the package using require as you have. Turns out it was an error on my part, I didn't realize that when TypeScript code gets compiled to CommonJS modules, default exports are a little weird. 

It should work if you change your import to be: `const Govee = require('govee-ts').default;`

I released a new version with an updated README that has instructions for using `require()` with this library. Hopefully this works for you, if so I can go ahead and close the issue.
